# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'JamStart2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Core'
	pod ‘FacebookCore’
	pod ‘FacebookLogin’
	pod ‘FirebaseUI/Facebook’
    pod 'FBSDKCoreKit'
    pod 'FirebaseDatabase'
    pod 'FirebaseAuth'
    pod 'Kingfisher', '~> 3.0'
    
end
